# -*- coding: utf-8 -*-
"""1-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJedecJ6dW4M6HHx-yMD1hEob42G2Ftu
"""

sum_value = 0
num = [int(input()) for _ in range(9)]
total_sum = sum(num)
num.sort()

found = False
for i in range(8):
    for j in range(i + 1, 9):
        if total_sum - num[i] - num[j] == 100:
            for k in range(9):
                if k != i and k != j:
                    print(num[k])
            found = True
            break

    if found:
        break