# -*- coding: utf-8 -*-
"""1-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LyKVhQ_BwJWI-i6tt0X7FRyNdId4iHm
"""

from itertools import combinations
# 모든 카드 리스트에 저장
num = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10]

# 땡인지 아닌지 체크하는 플래그
Twosame = False

A, B = map(int, input().split())

# 영학이가 뽑은 카드는 제외
num.remove(A)
num.remove(B)

# 땡인지 아닌지 체크
for i in range(1, 11):
  if A == i and B == i:
    Twosame = True
    break

# 땡일 때 영학이가 이길 확률은 1 - (영학이의 땡보다 높은 땡이 나올 경우 / 18개 중 2개를 무작위로 고르는 경우)
if Twosame:
  result = 1 - ((10-i)/153)
  print(f"{result:.3f}")

else:
  digit = (A+B)%10
  cnt = 0

  for i in range(18):
    for j in range(i+1, 18):
      if num[i] != num[j] and (num[i]+num[j])%10 < digit:
        cnt += 1

  # 끗일 때,영학이가 이길 확률은 (상대가 영학이보다 낮은 끗을 고르는 경우 / 18개 중 2개를 무작위로 고르는 경우)
  result = cnt/153
  print(f"{result:.3f}")

