# -*- coding: utf-8 -*-
"""1-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_x7OHEzXXtupmDdHUHG07ozONslfehx
"""

N, M = map(int, input().split())
board = [] # 원래 판
count = []

for _ in range(N):
  board.append(input())

# a는 8X8 판의 가로 시작점, b는 세로 시작점N-(7에서 시작해도 최소 길이가 8이 될 수 있게끔)
for a in range(N-7):
  for b in range(M-7):
    indexW = 0 # 체스판이 W로 시작할 경우 바뀌어야 할 체스판의 개수
    indexB = 0 # 체스판이 B로 시작할 경우 바뀌어야 할 체스판의 개수
    # 가능한 모든 8X8 체스판 고려
    for i in range(a, a+8):
      for j in range(b, b+8):
        if (i+j) % 2 == 0:
          if board[i][j] != 'W':
            indexW += 1
          if board[i][j] != 'B':
            indexB += 1
        else:
          if board[i][j] != 'B':
            indexW += 1
          if board[i][j] != 'W':
            indexB += 1
    count.append(indexW)
    count.append(indexB)

print(min(count))