# -*- coding: utf-8 -*-
"""1-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-G58frvSxa71LKHHo6_fP8K4UILjw5M
"""

N, M = map(int, input().split())
max_size = min(N, M) # 최대 정사각형 변의 길이는 직사각형의 짧은 변 길이를 넘어갈 수 없음
largest = 1
mylist = [list(map(int,input())) for _ in range(N)]

# 모든 꼭짓점 (i, j) 탐색
for i in range(N):
  for j in range(M):
    for k in range(1, max_size): # k는 탐색중인 정사각형의 변의길이-1 , 정사각형은 (k+1) *(k+1)
      if i + k < N and j + k < M: # 정사각형의 꼭짓점들이 직사각형을 벗어나지 않게끔
        if (mylist[i][j] == mylist[i][j + k] and
            mylist[i][j] == mylist[i + k][j] and
            mylist[i][j] == mylist[i + k][j + k]):
            largest = max(largest, (k + 1) ** 2)

print(largest)
