# -*- coding: utf-8 -*-
"""2-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQtFMdrooB0eYdW4BKXskK14EJNIj0mz
"""

M = int(input())

# 각 위치에 몇번 컵이 있는지 저장하기 위한 리스트(초기값: cup[1]에는 1이, cup[2]에는 2, cup[3]에는 3이 오게끔)
cup = [0, 1, 2, 3]

for i in range(M):
  X, Y = map(int, input().split())
  # X와 Y는 컵의 번호, swap1과 swap2는 컵의 위치를 저장
  for i in range(1, 4):
    if cup[i] == X:
      swap1 = i
    if cup[i] == Y:
      swap2 = i
  # 각 위치에 있는 컵을 교환
  temp = cup[swap1]
  cup[swap1] = cup[swap2]
  cup[swap2] = temp

# 공이 사라져서 컵 밑에 없는 경우 -1 출력
if swap1 == 0 or swap2 ==0:
  print(-1)

print(cup[1])
